get:
  tags:
    - iptv
  summary: Список сервисов IPTV
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/services.yaml"
  security:
    - USERSID: [ ]
