CREATE TABLE IF NOT EXISTS `internet_online` (
  `status`                     INT(3)               NOT NULL DEFAULT '0',
  `user_name`                  VARCHAR(32)          NOT NULL DEFAULT '',
  `started`                    DATETIME             NOT NULL,
  `nas_ip_address`             INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `nas_port_id`                INT(6) UNSIGNED      NOT NULL DEFAULT '0',
  `acct_session_id`            VARCHAR(40)          NOT NULL DEFAULT '',
  `acct_session_time`          INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `acct_input_octets`          BIGINT(14) UNSIGNED  NOT NULL DEFAULT '0',
  `acct_output_octets`         BIGINT(14) UNSIGNED  NOT NULL DEFAULT '0',
  `ex_input_octets`            BIGINT(14) UNSIGNED  NOT NULL DEFAULT '0',
  `ex_output_octets`           BIGINT(14) UNSIGNED  NOT NULL DEFAULT '0',
  `connect_term_reason`        SMALLINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `framed_ip_address`          INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `framed_ipv6_prefix`         VARBINARY(16)        NOT NULL DEFAULT '',
  `delegated_ipv6_prefix`      VARBINARY(16)        NOT NULL DEFAULT '',
  `framed_interface_id`        VARBINARY(16)        NOT NULL DEFAULT '',
  `lupdated`                   INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `sum`                        DOUBLE(14, 6)        NOT NULL DEFAULT '0.000000',
  `cid`                        VARCHAR(20)          NOT NULL DEFAULT '',
  `connect_info`               VARCHAR(35)          NOT NULL DEFAULT '',
  `tp_id`                      SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `nas_id`                     SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `acct_input_gigawords`       SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `acct_output_gigawords`      SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_input_octets_gigawords`  SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `ex_output_octets_gigawords` SMALLINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `uid`                        INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `join_service`               INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  `turbo_mode`                 VARCHAR(30)          NOT NULL DEFAULT '',
  `guest`                      TINYINT(1) UNSIGNED  NOT NULL DEFAULT '0',
  `circuit_id`                 VARCHAR(25)          NOT NULL DEFAULT '',
  `remote_id`                  VARCHAR(25)          NOT NULL DEFAULT '',
  `hostname`                   VARCHAR(30)          NOT NULL DEFAULT '',
  `switch_port`                VARCHAR(11)          NOT NULL DEFAULT '',
  `vlan`                       SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `server_vlan`                SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `switch_mac`                 VARCHAR(17)          NOT NULL DEFAULT '',
  `dhcp_id`                    TINYINT(2)           NOT NULL DEFAULT '0',
  `dhcp_ends`                  DATETIME             NOT NULL,
  `service_id`                 INT(11) UNSIGNED     NOT NULL DEFAULT '0',
  KEY `user_name` (`user_name`),
  KEY `acct_session_id` (`acct_session_id`),
  KEY `framed_ip_address` (`framed_ip_address`),
  KEY `service_id` (`service_id`),
  KEY `nas_id` (`nas_id`),
  KEY `uid` (`uid`),
  KEY `switch_mac` (`switch_mac`)
)
  DEFAULT CHARSET = utf8
  COMMENT ='Internet online';
