#!/bin/bash
### BEGIN INIT INFO
# Provides:          pppoe
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin
FLAGS="defaults 50"

LOCAL_IP=192.100.0.1
IFACE=eth0

case "$1" in
  start)
    echo "Starting PPPoE.... "
    echo "  Starting PPPoE on VLAN..."
    /usr/sbin/pppoe-server -N 1000 -k -L ${LOCAL_IP}  -I ${IFACE} 
    echo "pppoe."
    ;;
  stop)
    echo -n "Stopping PPPoE: "
    killall -9 pppd
    killall pppoe-server
    echo "pppoe."
    ;;
  force-reload|restart)
    echo "Restarting PPPoE: "
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/pppoe {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
