$lang{TRACKER} = 'Tracker';
$lang{TRACKERS} = 'Trackers';
$lang{TRACKED_ADMINS} = 'Tracked admins';
$lang{NOT_REGISTERED} = 'Not registered';
$lang{ROUTE_COLOR} = 'Route color';
$lang{ADMIN_ROUTES} = 'Admin routes';
$lang{FOR_TIME} = 'for time';
$lang{GPS_MAPS_SETTINGS} = 'Map Image Settings';
$lang{BATTERY} = 'Battery';