$lang{MAPS} = 'Карта Сеткі';
$lang{ANGLE} = 'Кут';
$lang{CLEAR} = 'Ачысціць';
$lang{HOUSE_NUM} = 'Нумар дома';
$lang{BUILD} = 'Дом';
$lang{FLAT} = 'кв.';
$lang{DEL_MARKER} = 'Маркер паспяхова выдалены';
$lang{DEL_DISTRICT} = 'Раён паспяхова выдалены са спісу';
$lang{ZOOM_IN} = 'Павялічыць';
$lang{ZOOM_OUT} = 'Зменшыць';
$lang{ZOOOM_IN_HERE} = 'Павялічыць тут';
$lang{ZOOOM_OUT_HERE} = 'Зменшыць тут';
$lang{CENTER_MAP_HERE} = 'Цэнтраваць карту';
$lang{ROUTES} = 'Маршруты';
$lang{ROUTE} = 'Маршрут';
$lang{FIELDS_FOR_NAME_ARE_REQUIRED} = 'Поле \'Назва\' абавязковая для запаўнення';
$lang{ADD_HOUSE} = 'Дадаць хату';
$lang{ADD_DISTRICT} = 'Дадаць раён';
$lang{ADD_ROUTE} = 'Дадаць маршрут';
$lang{CREATE_EDIT_ROUTE} = 'Стварыць/рэдагаваць маршрут';
$lang{COAXIAL} = 'Кааксіяльны';
$lang{FIBER_OPTIC} = 'Опта-валаконны';
$lang{HIDE_DISTRICTS} = 'Схаваць меню раёны';
$lang{SHOW_DISTRICTS} = 'Паказаць меню раёны';
$lang{IN_NEW_WINDOW} = 'У новым акне';
$lang{LINE} = 'Лінія';
$lang{DELETE_MARKER} = 'Выдаліць маркер';
$lang{ADD_WIFI_ZONE} = 'Дадаць Wi-Fi зону';
$lang{ADD_WIFI_RADIUS} = 'Дадаць зону пакрыцця';
$lang{WIFI_RADIUS} = 'Зона пакрыцця';
$lang{METERS_SHORT} = 'м.';
$lang{FIELDS_FOR_RADIUS_ARE_REQUIRED} = 'Поле \'Дадаць зону пакрыцця\' абавязковае для запаўнення';
$lang{ADD_WELL} = 'Дадаць студню';
$lang{ONLY_ONLINE} = 'Толькі анлайн';
$lang{ONLY_OFFLINE} = 'Толькі афлайн';
$lang{BUILD_NOT_FOUND} = 'Дом не дададзены на карту. ';
$lang{TWISTED_PAIR} = 'Кручаная пара';
$lang{BOXES} = 'Скрыні';
$lang{EDIT} = 'Рэдагаваць';

$lang{WIFI} = "Wi-Fi";
$lang{POINT} = 'Кропка';
$lang{BY_QUERY} = 'Па запыце';
$lang{BY_TYPE} = 'Па тыпе';
$lang{TOGGLE} = 'Пераключыць';
$lang{POLYGONS} = 'Палігоны';
$lang{MARKER} = 'Маркер';
$lang{CLUSTERS} = 'Кластэры';
$lang{LOCATION} = 'Месцазнаходжанне';
$lang{MAP_OBJECT_LAYERS} = 'Аб\'екты карты';
$lang{DROP} = 'Скінуць';
$lang{MAKE_ROUTE} = 'Разлічыць маршрут';
$lang{NOW_YOU_CAN_REMOVE_MARKER} = 'Зараз Вы можаце выдаліць маркер';
$lang{CLICK_ON_A_MARKER_YOU_WANT_TO_DELETE} = 'Націсніце на маркер, які жадаеце выдаліць';
$lang{NOW_YOU_CAN_ADD_NEW} = 'Зараз вы можаце дадаць ';
$lang{TO_MAP} = 'на карту';
$lang{NAVIGATION} = 'Навігацыя';
$lang{CUSTOM_POINT} = 'Асаблівы пункт';
$lang{NAVIGATION_WARNING} = "Вы забаранілі атрыманне каардынат вашай прылады або модуль GPS выключаны. Вы можаце гэта выправіць або перасунуць абразок карыстальніка на Вашае бягучае месцазнаходжанне для пошуку тэрміналаў аплат і дакладнага разліку маршрутаў";
$lang{DISTANCE} = 'Адлегласць';
$lang{AUTO_COORDS} = 'Запаўненне каардынат';
$lang{FAKE} = 'Несапраўдныя';
$lang{ERR_NOT_EXACT_RESULT} = 'Няма дакладнага выніку';
$lang{ERR_ZERO_RESULTS} = 'Няма вынікаў';
$lang{ERR_NOT_ONLY_RESULT} = 'Атрымана больш за адзін вынік';
$lang{FIBERS} = 'Валакна';
$lang{LINE_WIDTH} = 'Таўшчыня лініі';
$lang{PARENT_ROUTE} = 'Продак маршруту';
$lang{PARENT_F} = 'Бацькоўская';
$lang{PARENT_M} = 'Бацькоўскі';
$lang{LAYERS} = 'Пласты';
$lang{STRUCTURE} = 'Структура';
$lang{OBJECT_TYPES} = 'Тыпы аб\'ектаў';
$lang{ICONS} = 'Іконкі';
$lang{NO_ICONS} = 'Няма файлаў';
$lang{OBJECTS} = 'Аб\'екты';
$lang{OBJECT} = 'Аб\'ект';
$lang{MUFF} = 'Муфта';
$lang{SPLITTER} = 'Дзельнік';
$lang{CABLE} = 'Кабель';
$lang{PILLAR} = 'Апора';

$lang{CLOSEST} = 'Бліжэйшыя';

$lang{WELL} = 'Вузел сувязі';
$lang{WELLS} = 'Вузлы сувязі';

$lang{DISPLAYED_ITEMS} = "Адлюстравана элементаў";
$lang{DELETE} = "Выдаліць";

$lang{DELETE_ITEM_FROM_MAP} = "Выдаліць аб\'ект з карты?";
$lang{CHOOSE_ADDRESS} = "Абярыце адрас";

$lang{FEEL_ALL} = 'Запоўніць усё';
$lang{SEVERAL_RESULTS} = 'Некалькі вынікаў';
$lang{COORDS_NOT_FOUND} = 'Не знойдзена';
$lang{NO_COORDINATES_SPECIFIED} = 'Не пазначаны каардынаты';

$lang{COMPLETE_PREVIOUS_CHANGE} = 'Завершыце папярэднія змены';

$lang{SHOW_MSGS_MAP} = 'Паказваць паведамленне на карце';
$lang{MAPS_SCALE} = 'Маштаб';

1;