SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `cams_tp` (
  `tp_id` SMALLINT(6) UNSIGNED DEFAULT '0',
  `streams_count` SMALLINT(6) UNSIGNED DEFAULT 0,
  `dvr` SMALLINT(6) UNSIGNED DEFAULT 0,
  `ptz` SMALLINT(6) UNSIGNED DEFAULT 0,
  `archive` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `service_id` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  KEY `tp_id` (`tp_id`)
)
  DEFAULT CHARSET=utf8 COMMENT='Cams tariff plans';

CREATE TABLE IF NOT EXISTS `cams_main` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT(11) UNSIGNED DEFAULT 0,
  `tp_id` SMALLINT(6) UNSIGNED DEFAULT 0,
  `activate` DATETIME DEFAULT NULL,
  `status` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `subscribe_id` VARCHAR(32) NOT NULL DEFAULT '',
  `expire` DATE NOT NULL DEFAULT '0000-00-00',
  KEY `uid` (`uid`), 
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET=utf8 COMMENT='Users subscribed to cams';

CREATE TABLE IF NOT EXISTS `cams_streams` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  `disabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(32) NOT NULL DEFAULT '',
  `title` VARCHAR(32) NOT NULL DEFAULT '',
  `host` VARCHAR(128) NOT NULL DEFAULT '0.0.0.0',
  `rtsp_path` TEXT,
  `rtsp_port` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '554',
  `login` VARCHAR(32) NOT NULL DEFAULT '',
  `password` BLOB NOT NULL,
  `orientation` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `group_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `extra_url` VARCHAR(64) NOT NULL DEFAULT '',
  `screenshot_url` VARCHAR(64) NOT NULL DEFAULT '',
  `pre_image_url` VARCHAR(128) NOT NULL DEFAULT '',
  `coordx` DOUBLE(20,14) NOT NULL DEFAULT '0.00000000000000',
  `coordy` DOUBLE(20,14) NOT NULL DEFAULT '0.00000000000000',
  `transport` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `limit_archive` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `pre_image` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `constantly_working` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `archive` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `only_video` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `point_id` INT(11) UNSIGNED DEFAULT NULL,
  `angel` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `length` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `location_angel` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `number_id` VARCHAR(32) NOT NULL DEFAULT '',
  `folder_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
)
  DEFAULT CHARSET=utf8 COMMENT='Storing all streams';

CREATE TABLE IF NOT EXISTS `cams_services` (
  `id` TINYINT(2) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `module` VARCHAR(24) NOT NULL DEFAULT '',
  `status` TINYINT(2) UNSIGNED NOT NULL DEFAULT '0',
  `comment` VARCHAR(250) DEFAULT '',
  `login` VARCHAR(72) NOT NULL DEFAULT '',
  `password` BLOB,
  `url` VARCHAR(120) NOT NULL DEFAULT '',
  `user_portal` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `debug` TINYINT(2) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
)
  DEFAULT CHARSET=utf8 COMMENT='Cams Services';

CREATE TABLE IF NOT EXISTS `cams_groups` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `location_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `district_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `street_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `build_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `comment` VARCHAR(250) DEFAULT '',
  `max_users` SMALLINT(6) UNSIGNED DEFAULT 0,
  `max_cameras` SMALLINT(6) UNSIGNED DEFAULT 0,
  `service_id` INT(6) UNSIGNED NOT NULL DEFAULT 0,
  `subgroup_id` VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'External group ID for syncronization',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
)
  DEFAULT CHARSET=utf8 COMMENT='Cams Groups';

CREATE TABLE IF NOT EXISTS `cams_users_groups` (
  `id` INTEGER(10) UNSIGNED NOT NULL DEFAULT '0',
  `tp_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `group_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `changed` DATETIME NOT NULL,
  UNIQUE KEY `id` (`id`, `group_id`, `tp_id`)
)
  DEFAULT CHARSET=utf8 COMMENT = 'Cams users groups';

CREATE TABLE IF NOT EXISTS `cams_users_cameras` (
  `id` INTEGER(10) UNSIGNED NOT NULL DEFAULT '0',
  `tp_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `camera_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `changed` DATETIME NOT NULL,
  UNIQUE KEY `id` (`id`, `tp_id`, `camera_id`)
)
  DEFAULT CHARSET=utf8 COMMENT = 'Cams users cameras';

CREATE TABLE IF NOT EXISTS `cams_users_folders` (
  `id` INTEGER(10) UNSIGNED NOT NULL DEFAULT '0',
  `tp_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `folder_id` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `changed` DATETIME NOT NULL,
  UNIQUE KEY `id` (`id`, `folder_id`, `tp_id`)
)
  DEFAULT CHARSET=utf8 COMMENT = 'Cams users folders';

CREATE TABLE IF NOT EXISTS `cams_folder` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL DEFAULT '',
  `comment` VARCHAR(250) DEFAULT '',
  `parent_id` INT(6) UNSIGNED NOT NULL DEFAULT 0,
  `group_id` INT(6) UNSIGNED NOT NULL DEFAULT 0,
  `service_id` INT(6) UNSIGNED NOT NULL DEFAULT 0,
  `location_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `district_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `street_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `build_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `subfolder_id` VARCHAR(32) NOT NULL DEFAULT '',
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET=utf8 COMMENT='Cams Folder';