SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS push_contacts (
  `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `type` TINYINT(1) UNSIGNED,
  `client_id` SMALLINT(6) UNSIGNED,
  `endpoint` VARCHAR(210) NOT NULL,
  `key` VARCHAR(65) NOT NULL,
  `auth` VARCHAR(65) NOT NULL,
  UNIQUE `_type_id_endpoint` (`type`, `client_id`, `endpoint`, `auth`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS push_messages(
  `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `tag` VARCHAR(50) NOT NULL DEFAULT '',
  `contact_id` INT(11) UNSIGNED NOT NULL,
  `title` VARCHAR(64),
  `message` TEXT,
  `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ttl` INT(6) NOT NULL DEFAULT 86400
) DEFAULT CHARSET=utf8;