SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `turbo_mode` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mode_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `start` DATETIME NOT NULL  DEFAULT CURRENT_TIMESTAMP,
  `speed` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `speed_type` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `time` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`, `start`)
)
  COMMENT = 'Turbo mode Active Sessions';
