SET SQL_MODE = 'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO';

CREATE TABLE IF NOT EXISTS `vlan_main` (
  `uid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `vlan_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `ip` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `netmask` INT(10) UNSIGNED NOT NULL DEFAULT '4294967294',
  `disable` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `dhcp` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `nas_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0',
  `pppoe` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `unnumbered` TINYINT(10) UNSIGNED NOT NULL DEFAULT '0',
  `unnumbered_ip` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`),
  UNIQUE KEY `nas_id` (`nas_id`, `vlan_id`)
)
  COMMENT = 'Vlan user account';

