ALTER TABLE `cashbox_coming` ADD COLUMN `aid` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `cashbox_spending` ADD COLUMN `aid` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0;


ALTER TABLE msgs_unreg_requests ADD COLUMN `payment_sum` DOUBLE(14, 2) UNSIGNED NOT NULL DEFAULT '0.00';
ALTER TABLE msgs_unreg_requests ADD COLUMN `extra_sum` DOUBLE(14, 2) UNSIGNED NOT NULL DEFAULT '0.00';
ALTER TABLE msgs_unreg_requests ADD COLUMN `paid` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0';

