ALTER TABLE `cams_streams` ADD COLUMN `type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `msgs_dispatch` ADD COLUMN `created_by` SMALLINT(1) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `msgs_dispatch` ADD COLUMN `start_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `msgs_dispatch` ADD COLUMN `end_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `msgs_dispatch` ADD COLUMN `actual_end_date` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00';
ALTER TABLE `msgs_dispatch_admins` ADD FOREIGN KEY (`dispatch_id`) REFERENCES `msgs_dispatch`(`id`) ON DELETE CASCADE;