ALTER TABLE `internet_log` MODIFY COLUMN `nas_id` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `ring_rules` ADD COLUMN `update_day` VARCHAR(25) NOT NULL DEFAULT '';
ALTER TABLE `ring_rules` ADD COLUMN `sql_query` VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE `employees_rfid_log` MODIFY COLUMN `rfid` VARCHAR(15) NOT NULL DEFAULT '';
ALTER TABLE `crm_leads` ADD COLUMN `tag_ids` VARCHAR(20) NOT NULL DEFAULT '';

ALTER TABLE `storage_incoming` ADD COLUMN `invoice_number` VARCHAR(60) DEFAULT '';