CREATE TABLE IF NOT EXISTS `crm_dialogues` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lead_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `date` DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `source` VARCHAR(60) NOT NULL DEFAULT '',
  `aid` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0,
  `state` TINYINT(2) UNSIGNED DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE (`lead_id`, `date`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Crm dialogues';

CREATE TABLE IF NOT EXISTS `crm_dialogue_messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dialogue_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `date` DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` TEXT NOT NULL,
  `aid` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0,
  `inner_msg` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
)
  DEFAULT CHARSET = utf8
  COMMENT = 'Crm dialogue messages';

ALTER TABLE `crm_progressbar_step_comments` ADD COLUMN `pin` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0;