ALTER TABLE `callcenter_ivr_log` ADD COLUMN `lead_id` INT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `push_contacts`
    ADD COLUMN `badges` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `callcenter_ivr_log` ADD COLUMN `outgoing` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `callcenter_ivr_log` ADD COLUMN `aid` SMALLINT(6) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `callcenter_ivr_log` ADD COLUMN `call_record` VARCHAR(256) NOT NULL DEFAULT '';