ALTER TABLE `abon_tariffs` ADD COLUMN `activate_price` DOUBLE(14, 2) UNSIGNED NOT NULL DEFAULT '0.00';
ALTER TABLE `abon_tariffs` ADD COLUMN `promotional` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `abon_tariffs` ADD COLUMN `promo_period` SMALLINT(6) UNSIGNED NOT NULL DEFAULT '0';