get:
  tags:
    - config
  summary: Публичная конфигурация
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/publicConfig.yaml"
