$lang{STYLE} = 'Стиль';
$lang{DETAIL} = 'Подробнее';
$lang{AUTHOR} = 'Автор';
$lang{GALLERY_ON} = 'Включить галерею';
$lang{POSTS} = 'Посты';
$lang{PAGES} = 'Страницы';
$lang{GALLERY} = 'Галерея';
$lang{IMAGE_UPLOAD} = 'Загрузка картинки';
$lang{CHOOSE_IMAGES} = 'Выбрать картинки';
$lang{TITLE}= 'Заголовок';
$lang{DIR_CREATED}='Папка создана';
$lang{DESCRIPTION}='Описание';
1;