$lang{PAY_SYSTEM} = 'Systema de pago';
$lang{TRANSACTION} = 'Transacción';
$lang{TEST_MODE} = 'Modo de prueba';
$lang{ERR_NO_TRANSACTION} = 'Transacción no existe';
$lang{TRANSACTION_PROCESSING} = 'Transacción esta processando...';
$lang{FAILED} = 'Transacción ha fallado';
$lang{ERR_INVALID_SIGNATURE} = 'La firma es mal';
$lang{ERR_TRANSACTION_DECLINED} = 'Transacción rechazada';
$lang{ERR_TERMINAL} = 'Error del Terminal';
$lang{GET_INVOICE} = 'Obtener factura';
$lang{INVOICE_SENDED} = 'Factura enviada';
$lang{TEST_PAYMENT} = 'Pago de prueba';
$lang{BINDING} = 'Binding';
$lang{TARIF_PLAN_SUM} = 'El importe del pago no podrá ser inferior a la cuota mensual de suscripción ';
$lang{ERR_SMALL_SUM} = 'El importe del pago no podrá ser inferior a ';
$lang{CANCEL_PAYMENTS} = 'Cancelar Pago';
$lang{BALANCE_RECHARCHE_SUM} = 'El importe del depósito';
$lang{CONFIRM_PAYMENT} = 'Confirmar Pago';
$lang{CHOOSE_SYSTEM} = 'Elija un método de pago';

$lang{UNKNOWN} = 'Desconocido';
$lang{COMPLETE} = 'Completado';
$lang{CANCELED} = 'Cancelado';
$lang{EXPIRED} = 'Expirado';
$lang{ERR_INCORRECT_CHECKSUM} = 'Suma de comprobación es incorrecta';
$lang{PAYMENT_ERROR} = 'Error del pago';
$lang{DUPLICATE} = 'Ya existe pago';
$lang{USER_ERROR} = 'Error de ID del usuario';
$lang{SMALL_PAYMENT_SUM} = 'Importe del pago es pequeño';
$lang{REGISTER_IN} = 'Por favor regístrese en ';
$lang{EVENTS} = 'Eventos';
#$lang{ERR_TRY_AGAIN}='Произошла ошибка, попробуйт еще раз';
#$lang{REGULAR_PAYMENT}='Регулярный платёж';
#$lang{ADD_INFO}='Дополнительная информация';
#$lang{EXCHANGE_RATES}='Курс валют';
#$lang{CURRENCY_BUY}='Покупка';
#$lang{CURRENCY_SALE}='Продажа';
#$lang{SERVICE_FEE}='Сервисный сбор';

$lang{ADD_INFO} = 'Información Adicional';
$lang{DOCUMENTATION} = 'Documentación';

1;
