get:
  tags:
    - services
  summary: Список всех услуг
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            $ref: "../schemas/services.yaml"
  security:
    - USERSID: [ ]