$lang{RING}='Ring';
$lang{RULE}='Правило';
$lang{RULES}='Правила';
$lang{ADD_RULE}='Додати правило';
$lang{FILE}='Файл';
$lang{UPLOAD}='Завантажити файл';
$lang{MESSAGE}='Повідомлення';
$lang{FILTER}='Фільтри користувачів';
$lang{SELECT}='Вибрати';
$lang{RULES_LIST}='Список правил';
$lang{WAITING}='Очікує';
$lang{SUCCESS}='Успішно';
$lang{INTERRUPTED}='Перервано';
$lang{ANSWERPHONE}='Автовідповідач';
$lang{NOT_AVAILABLE}='Не доступний';
$lang{EVERY_MONTH}='Кожен місяць';
$lang{UPDATE_DAY} = 'День оновлення';
$lang{SQL_QUERY} = 'SQL запит';
1