$lang{RING}='Ring';
$lang{RULE}='Rule';
$lang{RULES}='Rules';
$lang{ADD_RULE}='Add rule';
$lang{FILE}='File';
$lang{UPLOAD}='Upload file';
$lang{MESSAGE}='Message';
$lang{FILTER}='User\'s filter';
$lang{SELECT}='Choose';
$lang{RULES_LIST}='List of rules';
$lang{WAITING}='Waiting';
$lang{SUCCESS}='Success';
$lang{INTERRUPTED}='Interrupted';
$lang{ANSWERPHONE}='Answer phone';
$lang{NOT_AVAILABLE}='Not Available';
$lang{EVERY_MONTH}='Every month';
$lang{UPDATE_DAY} = 'Update day';
$lang{SQL_QUERY} = 'SQL query';
1