$lang{RING}='Ring';
$lang{RULE}='Правило';
$lang{RULES}='Правила';
$lang{ADD_RULE}='Добавить правило';
$lang{FILE}='Файл';
$lang{UPLOAD}='Загрузить файл';
$lang{MESSAGE}='Сообщение';
$lang{FILTER}='Фильтры пользователей';
$lang{SELECT}='Выбрать';
$lang{RULES_LIST}='Список правил';
$lang{WAITING}='Ожидает';
$lang{SUCCESS}='Успешно';
$lang{INTERRUPTED}='Прервано';
$lang{ANSWERPHONE}='Автоответчик';
$lang{NOT_AVAILABLE}='Не доступен';
$lang{EVERY_MONTH}='Каждый месяц';
$lang{UPDATE_DAY} = 'День обновления';
$lang{SQL_QUERY} = 'SQL запрос';
1