Service activation notification


LOGIN: %LOGIN%
PERIOD: %PERIOD%
%SUM%
UID: %UID%
TP_ID: %TP_ID%
_{TARIF_PLAN}_: %TP_NAME%
_{PRICE}_: %PRICE%
_{COMMENTS}_: %COMMENTS%
_{DEPOSIT}_: %DEPOSIT%
_{CREDIT}_: %CREDIT%
_{DATE}_: %ABON_DATE%
%BILL_ID%
%FEES_TYPE%
%CREATE_ACCOUNT%
E-mail: %EMAIL%
%ALERT%
DATETIME: %DATETIME%
NEXT_ABON_DATE: %NEXT_ABON_DATE%
%DISCOUNT%
%CREATE_DOCS%
%SEND_DOCS%
