get:
  tags:
    - voip
  summary: Получить список путей
  parameters:
    - name: pageRows
      in: query
      description: Количество записей
      schema:
        type: number
        default: 25
    - name: pg
      in: query
      description: Рабоатет вместе с pageRows, параметр отвечает с какой записи начинать возвращать в запите
      schema:
        example: 10
        default: 0
  responses:
    200:
      description: Успешное выполнение
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../schemas/routes.yaml"
    400:
      description: Нет услуги Voip
      content:
        application/json:
          schema:
            type: object
            properties:
              errno:
                type: integer
                example: 30012
              errstr:
                type: string
                example: Not active voip service
  security:
    - USERSID: []